GannettDigital/simulato

- test/acceptance/article-data.json
Updated the news articles with more generic stories for #8
> Updated news articles

- appveyor.yml
- package-lock.json
- package.json
Addresses #15 
Update appveyor config to start background process with the new path to react-scripts.cmd
> issue-15: update minimum simulato-test-site version

- CHANGELOG.md
- lib/util/validators/validate-actions.js
- lib/util/validators/validate-elements.js
- package-lock.json
- package.json
#12 
Also updated one message inside validate actions
> issue-12 Add component names in error messages for validate elements

- CHANGELOG.md
- package.json
- test/acceptance/components/view-story-modal.js
Issue #16
Updated preconditions to use the correct elements in acceptance tests
> issue-16: fixed precondition typos

- CHANGELOG.md
- README.md
- index.js
- lib/cli/commands/generate.js
- lib/cli/commands/run.js
- lib/errors/cli/cli-error.js
- lib/errors/cli/index.js
- lib/errors/cli/invalid-component-path.js
- lib/errors/cli/invalid-generation-technique.js
- lib/executor/driver-handler.js
- lib/runner/test-runner/test-runner.js
- package.json
- test/acceptance/config.js
- test/unit/lib/cli/commands/generate-tests.js
- test/unit/lib/cli/commands/index-tests.js
- test/unit/lib/cli/commands/run-tests.js
- test/unit/lib/errors/cli/cli-error-tests.js
- test/unit/lib/errors/cli/index-tests.js
- test/unit/lib/errors/cli/invalid-component-path-tests.js
- test/unit/lib/errors/cli/invalid-generation-technique-tests.js
- test/unit/lib/executor/driver-handler-tests.js
- test/unit/lib/runner/test-runner/test-runner-tests.js
- test/unit/lib/util/expected-state-tests.js
Updated CLI configuration to be exportable to file format, as well as saucelab configuration #7
> Issue 7 Updated CLI configuration to be exportable

- .travis.yml
> issue-19: add codecov to travis

- CHANGELOG.md
> issue-19: update changelog

- CHANGELOG.md
- README.md
- lib/executor/execution-engine/execution-engine.js
- lib/executor/executor-event-dispatch/register-executor-events.js
- lib/global-event-dispatch/register-global-events.js
- lib/planner/planner-event-dispatch/register-planner-events.js
- lib/planner/search-node.js
- lib/util/data-store.js
- lib/util/expected-state.js
- package-lock.json
- test/unit/lib/executor/execution-engine/execution-engine-tests.js
- test/unit/lib/executor/executor-event-dispatch/register-executor-events-tests.js
- test/unit/lib/global-event-dispatch/register-global-events-tests.js
- test/unit/lib/util/data-store-tests.js
- test/unit/lib/util/expected-state-tests.js
#10 
Also broke out data store from expected
data store is now passed in to actions, children, and events
> issue-10: assert on the data store

- CHANGELOG.md
- RELEASE.md
- package.json
> Issue-28 Added release document, bumped version number

- CHANGELOG.md
- lib/executor/execution-engine/execution-engine.js
- package-lock.json
- package.json
- test/unit/lib/executor/execution-engine/execution-engine-tests.js
> Issue-31: bug fix for action parameters during execution

- CHANGELOG.md
- README.md
> issue-42: add badges to readme

- docs/_data/navigation.yaml
- docs/_pages/bug-report-template.md
- docs/_pages/contributing-guidelines.md
> issue-39: Create bug template doc

- CHANGELOG.md
- docs/_pages/data-store.md
- lib/util/data-store.js
- test/unit/lib/util/data-store-tests.js
> issue-22: add has method to datastore

- CHANGELOG.md
- lib/cli/orchestration/before.js
- test/unit/lib/cli/orchestration/before-tests.js
- test/unit/lib/util/validators/validate-actions-tests.js
- test/unit/lib/util/validators/validate-components-tests.js
> issue-48 tunnel created before scripts ran

- docs/pull_request_template.md
Resolves #53.
- Add PR template
@GannettDigital/core-contributors
> issue-53 added PR template

- CHANGELOG.md
- lib/runner/test-runner/print-output.js
- test/unit/lib/runner/test-runner/print-output-tests.js
> Issue-51: Parent exit code set to 1 when child has an error

- test/unit/lib/util/saucelabs-tests.js
Resolves issue: #57
- Added unit tests for util/saucelabs.js
> issue-57: created unit tests for util/saucelabs.js

- CHANGELOG.md
- docs/_pages/release-notes.md
- package-lock.json
- package.json
Release for new version
- v0.3.4 released
> prepare for publish v0.3.4

- CHANGELOG.md
- lib/util/get-element-data.js
- test/unit/lib/util/get-element-data-tests.js
Resolves issue: #57
- unit tested get-element-data
> issue-57-8: unit tested get-element-data

- CHANGELOG.md
- docs/_pages/components.md
- docs/_pages/run-time-variables.md
- lib/executor/assertion-handler.js
- lib/executor/executor-event-dispatch/register-executor-events.js
- lib/planner/planner-event-dispatch/register-planner-events.js
- lib/planner/search-algorithms/forward-state-space-search-heuristic.js
- lib/planner/search-algorithms/forward-state-space-search.js
- lib/util/oracle.js
- package.json
- test/acceptance/components/news-article.js
- test/acceptance/components/view-story-modal.js
- test/unit/lib/executor/assertion-handler-tests.js
- test/unit/lib/executor/executor-event-dispatch/register-executor-events-tests.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-heuristic-tests.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-tests.js
- test/unit/lib/util/oracle-tests.js
Resolves issue: #79
- Add the ability to assert on the dataStore
- Explicity assert on either the pageState or the dataStore
> issue-79: assert on datastore

- CHANGELOG.md
- lib/planner/search-algorithms/forward-state-space-search-heuristic.js
- lib/planner/search-algorithms/forward-state-space-search.js
- test/acceptance/components/news-article.js
- test/acceptance/components/view-story-modal.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-heuristic-tests.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-tests.js
Resolves issue: #70
- Pass in parameters for preconditions during planning
- Update old forward state space search with some newer changes
> issue-70: pass in parameters for preconditions during planning

- CHANGELOG.md
- docs/_pages/release-notes.md
- package-lock.json
- package.json
> 0.4.0: prepare for release

- CHANGELOG.md
- lib/planner/apply-effects.js
- lib/planner/planner-event-dispatch/register-planner-events.js
- lib/planner/search-algorithms/forward-state-space-search-heuristic.js
- test/unit/lib/planner/apply-effects-tests.js
- test/unit/lib/planner/possible-actions-tests.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-heuristic-tests.js
Resolves issue: #95
- Factor out apply effects so it can be used in multiple algorithms
> issue-95: factor out apply effects

- CHANGELOG.md
- docs/_pages/release-notes.md
- package-lock.json
- package.json
> Prepare for v0.5.0 release

- CHANGELOG.md
- docs/_pages/release-notes.md
- lib/runner/reporters/basic-reporter.js
- package-lock.json
- package.json
- test/unit/lib/runner/reporters/basic-reporter-tests.js
Resolves issue: #73 
- Updated reporter to show action identifier when printing errors
> Issue 73: Updated Basic Reporter

- CHANGELOG.md
- lib/runner/reporters/basic-reporter.js
- lib/runner/test-runner/test-runner.js
- test/unit/lib/runner/reporters/basic-reporter-tests.js
- test/unit/lib/runner/test-runner/test-runner-tests.js
Resolves issue: #104
- Fixes bug for rerun testrunner exit code
> Issue-104: Fixed test runner exit code bug

- CHANGELOG.md
- docs/_pages/release-notes.md
- package-lock.json
- package.json
> Prepare for v0.5.2 release

- docs/_pages/cli.md
- index.js
- lib/cli/commands/generate.js
- lib/cli/commands/run.js
- lib/runner/test-runner/test-runner.js
- lib/util/config-handler.js
- lib/util/defaults.js
- test/acceptance/config.js
- test/unit/lib/cli/commands/generate-tests.js
- test/unit/lib/cli/commands/run-tests.js
- test/unit/lib/runner/test-runner/test-runner-tests.js
- test/unit/lib/util/config-handler-tests.js
- test/unit/lib/util/defaults-tests.js
Resolves issue: #112
- Added util/config-handler.js
- Run & Generate now use this to get all options needed to run
- Created defaults for ease of finding all simulato defaults
> issue-112 added config-handler.js

- CHANGELOG.md
- docs/_pages/configuration-file.md
- docs/_pages/quick-start-guide.md
- lib/errors/config/config-error.js
- lib/errors/config/index.js
- lib/errors/config/invalid-property.js
- lib/errors/config/type-error.js
- lib/errors/index.js
- lib/global-event-dispatch/register-global-events.js
- lib/util/config-handler.js
- lib/util/defaults.js
- lib/util/validators/index.js
- lib/util/validators/validate-config.js
- package.json
- test/unit/lib/errors/config/config-error-tests.js
- test/unit/lib/errors/config/index-tests.js
- test/unit/lib/errors/config/invalid-property-tests.js
- test/unit/lib/errors/config/type-error-tests.js
- test/unit/lib/errors/index-tests.js
- test/unit/lib/global-event-dispatch/register-global-events-tests.js
- test/unit/lib/util/config-handler-tests.js
- test/unit/lib/util/defaults-tests.js
- test/unit/lib/util/validators/index-tests.js
- test/unit/lib/util/validators/validate-config-tests.js
Resolves issue: #117 
- Validates the config and cli inputs
> Issue 117: Validate Config/CLI Input

- lib/util/config-handler.js
- test/unit/lib/util/config-handler-tests.js
Resolves issue: #117
- fixed big where resolve paths always did reportPath
> issue-117 fixed big where resolve paths always did reportPath

- CHANGELOG.md
- docs/_pages/release-notes.md
- package-lock.json
- package.json
> v0.6.0 prep for release

- CHANGELOG.md
- index.js
- lib/planner/search-algorithms/forward-state-space-search-heuristic.js
- package-lock.json
- package.json
- test/unit/index-tests.js
- test/unit/lib/planner/search-algorithms/forward-state-space-search-heuristic-tests.js
Resolves issue: #140 
- Add debug option to generate command
- Report progress after finding a path while generating in debug mode
> issue-140: add debug option and print planner progress

- CHANGELOG.md
- docs/_pages/home/current-notes.md
- package-lock.json
- package.json
> v0.6.2 prepped for publish

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
> v0.6.5 prep for publish

- CHANGELOG.md
- lib/util/get-element-data.js
- lib/util/page-state-handler.js
- package-lock.json
- package.json
- test/unit/lib/util/get-element-data-tests.js
- test/unit/lib/util/page-state-handler-tests.js
Resolves issue: #80 
- Batch requests when getting element data
> issue-80: batch when getting element data 

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
> prep for v0.7.0 release

- CHANGELOG.md
- docs/pages/documentation/cli.md
- docs/pages/documentation/configuration-file.md
- lib/runner/test-runner/test-report-handler.js
- lib/runner/writers/index.js
- lib/runner/writers/j-unit-writer.js
- lib/util/config/schema.js
- package-lock.json
- package.json
- test/unit/lib/runner/test-runner/test-report-handler-tests.js
- test/unit/lib/runner/writers/action-json-writer-tests.js
- test/unit/lib/runner/writers/index-tests.js
- test/unit/lib/runner/writers/j-unit-writer-tests.js
- test/unit/lib/runner/writers/write-json-to-disk-tests.js
- test/unit/lib/util/config/schema-tests.js
Resolves issue: #173
- Add JUnit reporter
> issue-173: add JUnit reporter

- CHANGELOG.md
- lib/executor/execution-engine/execution-engine-report-handler.js
> Issue #187: Bug fix for expectedState in report

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
> v0.7.2: Prep for release

- CHANGELOG.md
- lib/planner/search-algorithms/action-tree.js
- package-lock.json
- package.json
Resolves issue: #192 
- Fixed bug in single action generation
> issue-192 fixed generation bug

- lib/executor/execute-test-case.js
- package-lock.json
- test/unit/lib/executor/execute-test-case-tests.js
> Exposed Remote object from Selenium-Webdriver

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
> prep for release

- lib/planner/write-plans-to-disk.js
- test/unit/lib/planner/write-plan-to-disk-tests.js
- Change output test names, such that they are hashes of the test plan content
> Plan based test names

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- updating changelog and release notes for plan based test names
> updating release-notes and CHANGELOG.md

- CHANGELOG.md
- docs/pages/home/release-notes.md
- lib/planner/search-algorithms/offline-replanning.js
- lib/planner/test-planner.js
- package-lock.json
- package.json
- test/unit/lib/planner/search-algorithms/offline-replanning-tests.js
- test/unit/lib/planner/test-planner-tests.js
Resolves issue: #203 
- Enabled replanning support for actionTree algorithm
- Fixed replanning algorithm to output correctly when running with actionTree algorithm
> Issue 203: Adds support for replanning with the actionTree algorithm

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
Resolves issue: #206 
-Update the changelog and release notes for changes below
-Prepended test file name to test case name of action report for easy mapping and better debugging
> Add 0.8.6 release note

- lib/runner/reporters/basic-reporter.js
- lib/runner/test-runner/test-report-handler.js
- lib/runner/test-runner/test-runner.js
- package-lock.json
- test/unit/lib/runner/test-runner/test-report-handler-tests.js
- test/unit/lib/runner/test-runner/test-runner-tests.js
- test/unit/lib/util/validators/validate-components-tests.js
Resolves issue: # 215
- changes retry logic to immediately queue tests instead of batching them
> Change retry logic

- CHANGELOG.md
- package-lock.json
- package.json
- Bumped package version
- Updated dependencies
- Updated CHANGELOG
> prepping for new npm release, fixing a lot of security issues

- CHANGELOG.md
- docs/pages/home/release-notes.md
- package-lock.json
- package.json
> v0.11.0: cut a release
